# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Test with the dotnet CLI
      run: dotnet test
    - name: format
      run: dotnet format style
    - name: analyse
      uses: github/codeql-action/init@v3
      with:
        languages: c-cpp, csharp  
   # - name: Lint Code Base
     # uses: github/super-linter@v4
      #env:
     #   VALIDATE_ALL_CODEBASE: true
    #    VALIDATE_JAVASCRIPT_ES: true
   #     VALIDATE_PYTHON_BLACK: true
    #    VALIDATE_HTML: true
     #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#blam
     
